from sensor import Sensor
from insulin_pump import InsulinPump
from communication_channel import CommunicationChannel
import time
import csv
import statistics
import pandas as pd
import gc
import os
import memray
from memray import FileReader

def measure_computation(func, *args, **kwargs):
    start = time.perf_counter()
    #before = process.memory_info().rss
    result  = func(*args, **kwargs)
    end = time.perf_counter()
    #after = process.memory_info().rss
    elapsed = end-start
    #memory = after - before
    return result, elapsed

def store_stats(data, enc_type):
    mean_val = statistics.mean(data)
    median_val = statistics.median(data)
    df = pd.DataFrame({ #generated by Gemini
        'Encryption_Type':enc_type,
        'Raw_Data': data,
        'Mean': [mean_val] * len(data),
        'Median': [median_val] * len(data),
         })
    return df

def store_summary(enc_times, dec_times, full_memory, key_exchange, enc_type):
    mean_enc = statistics.mean(enc_times)
    mean_dec = statistics.mean(dec_times)
    #mean_enc_memory = statistics.mean(enc_memory)
    #mean_dec_memory = statistics.mean(dec_memory)
    df = pd.DataFrame({
        'Encryption_Algorithm': [enc_type],
        'Key_Exchange_Time': [key_exchange],
        'Average_Encryption_Time': [mean_enc],
        'Average_Decryption_Time': [mean_dec],
        #'Peak_Encryption_Memory': enc_memory,
        'Peak_Protocol_Memory': full_memory
    })
    return df

def aes_key_exchange(channel, test_sensor, test_insulin, key_len):
     #send cgm public key
    channel.send(test_sensor.return_public_key())
    test_insulin.key_exchange(channel.receive(), key_len)

    #sent aid public key
    channel.send(test_insulin.return_public_key())
    test_sensor.key_exchange((channel.receive()), key_len)

def full_session(enc_func, dec_func, key_len, final_dataset_collection, algo_name):
    gc.collect()
    test_sensor = Sensor(json_filepath = "sample_messages.json")
    test_insulin = InsulinPump()
    channel = CommunicationChannel()
    encryption_times = [0.0] * 1000 # to avoid the extra time/memory used for rearranging lists during append function
    decryption_times = [0.0] * 1000
    #enc_memory = []
    #dec_memory = []
    
    _, key_exchange_time  = measure_computation(aes_key_exchange,channel, test_sensor, test_insulin, key_len)
    
    print("Succesful key exchange")

    encryption = getattr(test_sensor, enc_func)
    decryption = getattr(test_insulin, dec_func)

    
#Measure only time related benchmarks
    enc_trace = f"{algo_name}_enc.bin"
    if os.path.exists(enc_trace):
        os.remove(enc_trace)
        
    with memray.Tracker(enc_trace, native_traces=True):
        for i in range (1000):
            test_sensor.prepare_plaintext()
            crypto_output, enc_time = measure_computation(encryption)
            ct, nonce = crypto_output
            encryption_times[i] = enc_time
            channel.send([ct, nonce])
            received_packet = channel.receive()
            plaintext, dec_time = measure_computation(decryption, received_packet[0], received_packet[1])
            decryption_times[i] = dec_time
    reader = FileReader(enc_trace)
    peak_protocol_memory = 0
    
    for allocation in reader.get_high_watermark_allocation_records(merge_threads=True): #generated by Gemini
        if allocation.size>peak_protocol_memory:
            peak_protocol_memory = allocation.size
        
    df = store_summary(encryption_times, decryption_times, peak_protocol_memory, key_exchange_time, algo_name)
    final_dataset_collection.append(df)
    

def main():

    final_dataset_collection = []
    dummy_data = []
    #TEST SESSION - NO PLOT
    full_session("aes_gcm_encryption", "decrypt_aes_gcm", 16, dummy_data, "TEST")
    
    
    full_session("aes_gcm_encryption", "decrypt_aes_gcm", 16, final_dataset_collection, "1_AES_GCM_128")
    print("New Session")
    full_session("aes_gcm_encryption", "decrypt_aes_gcm", 16, final_dataset_collection, "2_AES_GCM_128")
    print("New Session")
    full_session("aes_gcm_encryption", "decrypt_aes_gcm", 32, final_dataset_collection, "1_AES_GCM_256")
    print("New Session")
    full_session("aes_gcm_encryption", "decrypt_aes_gcm", 32, final_dataset_collection, "2_AES_GCM_256")
    print("New Session")
    full_session("aes_ccm_encryption", "decrypt_aes_ccm", 16, final_dataset_collection, "1_AES_CCM_128")
    print("New Session")
    full_session("aes_ccm_encryption", "decrypt_aes_ccm", 16, final_dataset_collection, "2_AES_CCM_128")
    print("New Session")
    full_session("aes_ccm_encryption", "decrypt_aes_ccm", 32, final_dataset_collection, "1_AES_CCM_256")
    print("New Session")
    full_session("aes_ccm_encryption", "decrypt_aes_ccm", 32, final_dataset_collection, "2_AES_CCM_256")
    print("New Session")
    full_session("chacha_encryption", "decrypt_chacha", 32, final_dataset_collection, "1_CHACHA_256") #only can use a 32 byte key for ChaCha Encryption
    print("New Session")
    full_session("chacha_encryption", "decrypt_chacha", 32, final_dataset_collection, "2_CHACHA_256")
    print("New Session")
        # Re-calls main.py passing '--worker' and configuration arguments - generated by Gemini
        #result = subprocess.run([sys.executable, __file__, "--worker"] + task, capture_output=True, text=True)
    
    df_final = pd.concat(final_dataset_collection, ignore_index = True)
    df_final.to_csv('results.csv' ,index=False)
    
if __name__ == "__main__":
    main()
