from sensor import Sensor
from insulin_pump import InsulinPump
from communication_channel import CommunicationChannel
import time
import csv
import statistics
import pandas as pd


def measure_time(func, *args, **kwargs):
    start = time.perf_counter()
    result  = func(*args, **kwargs)
    end = time.perf_counter()
    elapsed = end-start
    return result, elapsed

def store_stats(data):
    mean_val = statistics.mean(data)
    median_val = statistics.median(data)
    df = pd.DataFrame({ #generated by Gemini
        'Raw_Data': data,
        'Mean': [mean_val] * len(data),
        'Median': [median_val] * len(data),
         })
    return df

def main():
    test_sensor = Sensor(json_filepath = "sample_messages.json")
    test_insulin = InsulinPump()
    channel = CommunicationChannel()
    encryption_times = []
    decryption_times = []
    
    #send cgm public key
    channel.send(test_sensor.return_public_key())
    test_insulin.key_exchange(channel.receive())

    #sent aid public key
    channel.send(test_insulin.return_public_key())
    test_sensor.key_exchange((channel.receive()))

    print("Succesful key exchange")

    for i in range (8):
        crypto_output, enc_time = measure_time(test_sensor.aes_encryption)
        ct, nonce = crypto_output
        encryption_times.append(enc_time)
        channel.send([ct, nonce])
        received_packet = channel.receive()
        plaintext, dec_time = measure_time(test_insulin.decrypt_aes, received_packet[0], received_packet[1])
        decryption_times.append(dec_time)
        print("Decryption complete!")
        print(plaintext)

    df = store_stats(encryption_times)
    df.to_csv('encrypt_latency_data.csv', index=False)
    df = store_stats(decryption_times)
    df.to_csv('decrypt_latency_data.csv', index=False)
    
if __name__ == "__main__":
    main()
